FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Customer

Customer adds product to the shopping cart

## Create Order [/createOrder]

### Customer adds products to shopping cart [POST]

+ Request (application/json)

        {
            "text": "Please Enter the following: ",
            "fields": [
                "Product ID: ",
                "Deal ID: ",
                "Quantity: "
            ]
        }


+ Response 200 (application/json)

        [
            {
              "message":"Your orer has been saved successfully."
            }
        ]


# Vendor Admin

Deals by Vendors        
        
## Create Deals [/createDeals]

### Vendor creates the deal [POST]

+ Request (application/json)

        {
            "text": "Please Enter the following: ",
            "fields": [
                "Product ID: ",
                "Deal ID: ",
                "Quantity: "
            ]
        }


+ Response 200 (application/json)

        [
            {
              "message":"Your orer has been saved successfully."
            }
        ]